title = "mage api config"

[mongo]
url = "mongodb+srv://erdem:5375Erdem@cluster0.yh5hk3t.mongodb.net/?retryWrites=true&w=majority"
database = "mage"
max_open = 20
max_idle = 5

[api]
host = "127.0.0.1"
port = "8080"